# Generated by Django 5.1.7 on 2025-03-19 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='branch_from',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='branch_to',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.customerprofile'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
