# Generated by Django 5.1.7 on 2025-03-19 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_remove_parcel_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_parcels', to='courier.customerprofile'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='branch_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels_sent', to='courier.branch'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='branch_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels_received', to='courier.branch'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_parcels', to='courier.customerprofile'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
