# Generated by Django 5.1.7 on 2025-03-20 04:28

import courier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_parcel_delivery_date_parcel_pickup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(default=courier.models.generate_unique_tracking_number, editable=False, max_length=6, unique=True),
        ),
    ]
