# Generated by Django 5.1.7 on 2025-03-20 05:08

import courier.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_remove_parcel_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(default=courier.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
