# Generated by Django 5.1.7 on 2025-03-20 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0007_parcel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
