# Generated by Django 5.1.7 on 2025-03-20 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0008_alter_parcel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.customerprofile'),
        ),
    ]
