# Generated by Django 5.1.7 on 2025-03-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0009_alter_parcel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
