# Generated by Django 5.1.7 on 2025-03-23 05:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0010_alter_parcel_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='sent_date',
        ),
        migrations.AddField(
            model_name='parcel',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_parcels', to='courier.customerprofile'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='branch_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels_sent', to='courier.branch'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='branch_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels_received', to='courier.branch'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='dimensions',
            field=models.CharField(default=datetime.datetime(2025, 3, 23, 5, 32, 46, 904691, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_parcels', to='courier.customerprofile'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
