# Generated by Django 5.1.7 on 2025-03-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0011_remove_parcel_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='dimensions',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.FloatField(),
        ),
    ]
