# Generated by Django 5.1.7 on 2025-03-26 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0016_parcel_created_by_staff'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_parcels', to='courier.customerprofile'),
        ),
    ]
