# Generated by Django 5.1.7 on 2025-03-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0017_alter_parcel_created_by_staff_alter_parcel_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='sender',
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender_name',
            field=models.CharField(default='Unknown Sender', max_length=255),
        ),
    ]
